<a href="https://colab.research.google.com/github/gesaneubauer/AdvancesDataMining/blob/main/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files, drive
import numpy as np
import pandas as pd
import argparse


def load_data():
    drive.mount('/content/drive')
    file_path = '/content/drive/My Drive/user_movie_rating.npy'
    data = np.load(file_path)
    return data

data = load_data()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [16]:
print(data[:])

[[     1     30      3]
 [     1    157      3]
 [     1    173      4]
 ...
 [103703  17622      2]
 [103703  17627      4]
 [103703  17764      4]]


In [2]:
def main(file_path, seed, similarity_measure):
    # Set the random seed for reproducibility
    np.random.seed(seed)

    # Load the data from the specified file
    data = load_data(file_path)

    # Preprocess the data to get it into the required format
    processed_data = preprocess_data(data)

    # Initialize the LSH algorithm based on the chosen similarity measure
    if similarity_measure == 'cs':
        # Initialize LSH for Cosine
        pass
    elif similarity_measure == 'js':
        # Initialize LSH for Jaccard Similarity
        pass
    elif similarity_measure == 'dcs':
        # Initialize LSH for Discrete Cosine Similarity
        pass
    else:
        raise ValueError("Invalid similarity measure. Choose 'cs', 'js', or 'dcs'.")

    # Fit the LSH model and find similar pairs
    lsh.fit(processed_data)
    similar_pairs = lsh.find_similar_pairs()

    # Output results
    output_file = f'{similarity_measure}.txt'
    with open(output_file, 'w') as f:
        for pair in similar_pairs:
            f.write(f'{pair[0]}, {pair[1]}\n')

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="LSH for finding similar user pairs")
    parser.add_argument('-d', '--data', required=True, help="Path to data file")
    parser.add_argument('-s', '--seed', type=int, default=17, help="Random seed")
    parser.add_argument('-m', '--measure', required=True, choices=['cs', 'js', 'dcs'], help="Similarity measure (cs, js, dcs)")
    args = parser.parse_args()

    main(args.data, args.seed, args.measure)


ModuleNotFoundError: ignored